FROM python:3.13-slim

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY . /app

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app/src

RUN uv sync --all-groups

CMD ["uv", "run", "pytest", "-vv", "tests"]
