"""Repository mixins and base classes for v2."""

from .base import Repository, SoftDeleteRepository
from .mixins import (
    CountableMixin,
    CreatableMixin,
    DeleteMixin,
    FilterableMixin,
    ListableMixin,
    LoadOptionsMixin,
    OrderableMixin,
    PrimaryKeyMixin,
    RetrievableMixin,
    SelectableMixin,
    SoftDeleteMixin,
    UpdateMixin,
    UpsertableMixin,
    UpsertOrSkipMixin,
)
from .types import (
    FilterClause,
    FilterFactory,
    FilterSpec,
    OptionFactory,
    OptionSpec,
    OrderClause,
    OrderFactory,
    OrderSpec,
    SupportsOptions,
    SupportsWhere,
)

__all__ = [
    'CountableMixin',
    'CreatableMixin',
    'DeleteMixin',
    'FilterClause',
    'FilterFactory',
    'FilterSpec',
    'FilterableMixin',
    'ListableMixin',
    'LoadOptionsMixin',
    'OptionFactory',
    'OptionSpec',
    'OrderClause',
    'OrderFactory',
    'OrderSpec',
    'OrderableMixin',
    'PrimaryKeyMixin',
    'Repository',
    'RetrievableMixin',
    'SelectableMixin',
    'SoftDeleteMixin',
    'SoftDeleteRepository',
    'SupportsOptions',
    'SupportsWhere',
    'UpdateMixin',
    'UpsertOrSkipMixin',
    'UpsertableMixin',
]
