"""Next-generation repository and service toolkit."""

from notora.v2.fastapi import make_list_params_dependency
from notora.v2.repositories import (
    FilterClause,
    FilterFactory,
    FilterField,
    FilterSpec,
    OptionFactory,
    OptionSpec,
    OrderClause,
    OrderFactory,
    OrderSpec,
    PaginationParams,
    QueryInput,
    QueryParams,
    RepoConfig,
    Repository,
    SoftDeleteRepository,
    SortField,
    apply_filter_operator,
    build_query_params,
    make_query_params_dependency,
    resolve_to_column,
)
from notora.v2.schemas import (
    BaseRequestSchema,
    BaseResponseSchema,
    ClientMeta,
    PaginatedResponseSchema,
    PaginationMetaSchema,
    PydanticFilterField,
    PydanticFiltersSchema,
    PydanticOrderBySchema,
    PydanticSortField,
)
from notora.v2.services import (
    RepositoryService,
    ServiceConfig,
    SoftDeleteRepositoryService,
)

__all__ = [
    'BaseRequestSchema',
    'BaseResponseSchema',
    'ClientMeta',
    'FilterClause',
    'FilterFactory',
    'FilterField',
    'FilterSpec',
    'OptionFactory',
    'OptionSpec',
    'OrderClause',
    'OrderFactory',
    'OrderSpec',
    'PaginatedResponseSchema',
    'PaginationMetaSchema',
    'PaginationParams',
    'PydanticFilterField',
    'PydanticFiltersSchema',
    'PydanticOrderBySchema',
    'PydanticSortField',
    'QueryInput',
    'QueryParams',
    'RepoConfig',
    'Repository',
    'RepositoryService',
    'ServiceConfig',
    'SoftDeleteRepository',
    'SoftDeleteRepositoryService',
    'SortField',
    'apply_filter_operator',
    'build_query_params',
    'make_list_params_dependency',
    'make_query_params_dependency',
    'resolve_to_column',
]
